development:
  adapter: postgresql
  encoding: unicode
  database: todo_app_back_end_development

test:
  adapter: postgresql
  encoding: unicode
  database: todo_app_back_end_test

production:
  adapter: postgresql
  encoding: unicode
  database: todo_app_back_end_production
